version: "3.3"
services:
  frontend:
    container_name: frontend
    ports:
      - "5173:5173"
    image: vijikalavarkar/mernappfr:v1

  backend:
    container_name: backend
    ports:
      - "5050:5050"
    image: vijikalavarkar/mernappbk:v1

 