version: "3.3"
services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "5173:5173"
    

  backend:
    container_name: backend
    build: ./backend
    ports:
      - "5050:5050"
    

 